// Author-side impls for the cel_wasm_component demo fixture.
// Implements the declarations in fns.idl; everything else is
// generated by the macro pipeline (codec.h, generated_stub.cc,
// customfn.h, user_fns.h).

#include "user_fns.h"

#include <string>
#include <string_view>

namespace customfn {

std::string Greet(std::string_view name, int64_t age) {
  return std::string("Hello, ") + std::string(name) + " (age " +
         std::to_string(age) + ")";
}

int64_t Add(int64_t a, int64_t b) {
  return a + b;
}

int64_t Len(std::string_view s) {
  return static_cast<int64_t>(s.size());
}

}  // namespace customfn
