// Embedded bytes for the wasm32 build of `cel_runtime.c`.
//
// Generated by //runtime:cel_runtime_wasm_bytes_cc from the
// output of //runtime:cel_runtime_wasm_file (a genrule that
// cross-compiles the C source with brew's `/opt/homebrew/opt/llvm/bin/clang`
// against a freestanding wasm32 target).  Host-side loader code
// instantiates these bytes as the runtime module, with its imported
// `cel.memory` bound to the expr module's exported memory.
//
// The bytes are linked in as a plain C array to keep the dependency
// surface small — no runfiles lookup, no `std::ifstream`, no filesystem
// dependency at load time.

#ifndef CELWASM_COMPILER_V2_RUNTIME_CEL_RUNTIME_WASM_BYTES_H_
#define CELWASM_COMPILER_V2_RUNTIME_CEL_RUNTIME_WASM_BYTES_H_

namespace celwasm {

extern const unsigned char kCelRuntimeWasmBytes[];
extern const unsigned int kCelRuntimeWasmBytesSize;

}  // namespace celwasm

#endif  // CELWASM_COMPILER_V2_RUNTIME_CEL_RUNTIME_WASM_BYTES_H_
