// Code generated by celfnc. DO NOT EDIT.
//
// celfn_abi.go — the COMMON fixed-ABI machinery for a foreign-Go CEL library.
// One copy per module, identical regardless of which functions the .celfn
// declares. celfnc emits this verbatim; the per-function trampolines live in
// celfn_exports.go and the user's natural Go lives in their own file.
//
// This is the §5.3 / §5.6 (modules-and-ffi.md) producer contract for Go:
//   - celfn_realloc  : the cabi_realloc-shaped allocator the host calls to
//                      place inbound argument bytes into THIS module's memory.
//   - lift helpers   : decode the fixed-ABI arg forms (scalars by value;
//                      string/bytes/proto as (ptr,len)) out of this module's
//                      own linear memory into natural Go values.
//   - guard          : wraps each user call so a Go panic (explicit OR runtime,
//                      e.g. nil-deref / index-OOB) becomes a clean error status
//                      instead of a wasm trap. (Empirically: an uncaught panic
//                      unwinds to `unreachable`; recover() converts it.)
//   - main()         : required so the wasip1 reactor links.
//
// Build: GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared -o rules.wasm .
package main

import "unsafe"

// ── Allocator ───────────────────────────────────────────────────────────
//
// celfn_realloc(ptr, oldLen, align, newLen) -> ptr   (cabi_realloc shape)
//   ptr == 0     → fresh allocation of newLen bytes.
//   ptr != 0     → grow: copy old contents forward, drop the old pin.
//   newLen == 0  → 0.
// The returned address is the start of a Go-managed []byte's backing array;
// we keep it reachable in `argPins` so the GC neither moves nor frees it while
// the host writes into it and the trampoline runs. The host copies any result
// into the shared arena synchronously before the next foreign entry (§5.5), so
// a per-call reset of the pins is safe; ResetArgPins() exposes that.
//
//go:wasmexport celfn_realloc
func celfn_realloc(ptr, oldLen, align, newLen uint32) uint32 {
	if newLen == 0 {
		return 0
	}
	buf := make([]byte, newLen)
	p := uint32(uintptr(unsafe.Pointer(unsafe.SliceData(buf))))
	argPins[p] = buf
	if ptr != 0 {
		if old, ok := argPins[ptr]; ok {
			copy(buf, old)
			delete(argPins, ptr)
		}
	}
	return p
}

var argPins = map[uint32][]byte{}

// ResetArgPins drops all pinned arg buffers. A trampoline may call this on the
// way out (after the host has consumed the result) to bound memory growth.
func ResetArgPins() {
	clear(argPins)
}

// ── Lift helpers (fixed-ABI arg form → natural Go) ───────────────────────
//
// The bytes referenced by (ptr,len) live in THIS module's own memory; the host
// wrote them there via celfn_realloc immediately before the call and they are
// valid for the call's duration (§5.5). liftString/liftBytes are zero-copy
// views over that region — do not retain them past the call.

func liftString(ptr, length uint32) string {
	if length == 0 {
		return ""
	}
	return unsafe.String((*byte)(unsafe.Pointer(uintptr(ptr))), int(length))
}

func liftBytes(ptr, length uint32) []byte {
	if length == 0 {
		return nil
	}
	return unsafe.Slice((*byte)(unsafe.Pointer(uintptr(ptr))), int(length))
}

// Scalars cross flat on the wasm stack, so the "lift" is a plain Go cast the
// trampoline does inline (i32→bool, i64→int64, f64→float64). No helper needed;
// listed here for documentation parity with the §5.3 storage table.

// ── Panic guard ──────────────────────────────────────────────────────────
//
// guard runs `body` and reports whether it completed without panicking.
// ok == true  → body returned normally; the result the body wrote is valid.
// ok == false → body panicked; the trampoline must signal kError to the host
//               (via the status channel, see celfn_exports.go) and NOT trust
//               any result value. Catches explicit panic() and runtime panics
//               (nil deref, index out of range) alike.
func guard(body func()) (ok bool) {
	ok = true
	defer func() {
		if r := recover(); r != nil {
			ok = false
		}
	}()
	body()
	return
}

// ── Reactor entry ─────────────────────────────────────────────────────────
//
// Required for the GOOS=wasip1 -buildmode=c-shared reactor build to link.
// Never invoked at runtime; the host calls the module's `_initialize` export
// once after instantiation instead (skipping it traps).
func main() {}
