// Code generated by celfnc from rules.celfn. DO NOT EDIT.
//
// celfn_exports.go — the per-function TRAMPOLINES. One //go:wasmexport per
// foreign decl in the .celfn, named after its overload_id (CelfnDecl.overload_id).
// Each trampoline: lifts the fixed-ABI args (via celfn_abi.go helpers), calls
// the user's natural Go function under guard(), and reports (result, status).
//
// Status channel (the error half of the ABI): every export returns its real
// result PLUS a trailing status flag, packed so the host can tell a genuine
// `false`/`0` apart from a foreign failure (panic or a decode error). For a
// bool/scalar result we pack into one i64: low 32 bits = value, bit 32 = the
// CELFN_ERR flag. The host trampoline reads the flag → writes kError, else
// lifts the value. (Aggregate returns would use the §5.3 return area + a
// separate status word; the principle is the same.)
//
// The .celfn that generated this:
//   bool isValidName(string foo);
//   bool isAdult(proto(acme.User) user);

package main

import (
	"google.golang.org/protobuf/proto"

	userpb "layered/userpb"
)

// CELFN_ERR is OR'd into bit 32 of a scalar-return export when the call failed
// (panic / decode error). The host masks it off and treats it as kError.
const celfnErr uint64 = 1 << 32

func packBool(v bool) uint64 {
	if v {
		return 1
	}
	return 0
}

// ── isValidName ──────────────────────────────────────────────────────────
// IDL:        bool isValidName(string foo);
// overload:   isValidName_string
// arg form:   foo:string → (i32 ptr, i32 len)
// ret form:   bool → packed i64 (value | maybe CELFN_ERR)
//
//go:wasmexport isValidName_string
func isValidName_string(fooPtr, fooLen uint32) uint64 {
	var result bool
	ok := guard(func() {
		foo := liftString(fooPtr, fooLen)
		result = IsValidName(foo) // ← user stub
	})
	if !ok {
		return celfnErr
	}
	return packBool(result)
}

// ── isAdult ────────────────────────────────────────────────────────────────
// IDL:        bool isAdult(proto(acme.User) user);
// overload:   isAdult_message_acme_User
// arg form:   user:proto(acme.User) → (i32 ptr, i32 len) of serialized bytes
//             (§8.5 serialization path; host serializes, glue Unmarshals)
// ret form:   bool → packed i64
//
//go:wasmexport isAdult_message_acme_User
func isAdult_message_acme_User(userPtr, userLen uint32) uint64 {
	var result bool
	ok := guard(func() {
		var msg userpb.User
		if err := proto.Unmarshal(liftBytes(userPtr, userLen), &msg); err != nil {
			// A decode failure is a contract violation, not `false`. Panic so
			// guard() flags it as kError rather than masquerading as a result.
			panic(err)
		}
		result = IsAdult(&msg) // ← user stub
	})
	if !ok {
		return celfnErr
	}
	return packBool(result)
}
