package bench:abi@0.1.0;

interface engine {
  noop: func() -> u32;
  i64-3: func(a: s64, b: s64, c: s64) -> s64;
  i64-5: func(a: s64, b: s64, c: s64, d: s64, e: s64) -> s64;
  str-1: func(a: string) -> u32;
  str-3: func(a: string, b: string, c: string) -> u32;
  str-5: func(a: string, b: string, c: string, d: string, e: string) -> u32;
  bytes-1: func(a: list<u8>) -> u32;
  str-3-ret: func(a: string, b: string, c: string) -> string;
}

world engine-world { export engine; }
world runner-world { import engine; }
