// Author-side impls for the cel_wasm_plugin demo fixture.
// Implements the declarations in fns.idl; everything else is
// generated by the macro pipeline (codec.h, generated_stub.cc,
// customfn.h, user_fns.h).

#include "user_fns.h"

#include <cstdint>
#include <map>
#include <string>
#include <string_view>
#include <vector>

namespace customfn {

std::string Greet(std::string_view name, int64_t age) {
  return std::string("Hello, ") + std::string(name) + " (age " +
         std::to_string(age) + ")";
}

int64_t Add(int64_t a, int64_t b) {
  return a + b;
}

int64_t Len(std::string_view s) {
  return static_cast<int64_t>(s.size());
}

double EchoDouble(double d) {
  return d;
}

uint64_t EchoUint(uint64_t u) {
  return u;
}

std::string EchoString(std::string_view s) {
  return std::string(s);
}

bool Negate(bool b) {
  return !b;
}

std::vector<uint8_t> RevBytes(const std::vector<uint8_t>& b) {
  return {b.rbegin(), b.rend()};
}

std::vector<int64_t> EchoList(const std::vector<int64_t>& xs) {
  return xs;
}

std::map<std::string, int64_t> EchoMap(
    const std::map<std::string, int64_t>& m) {
  return m;
}

int64_t SumList(const std::vector<int64_t>& xs) {
  int64_t total = 0;
  for (int64_t x : xs) {
    total += x;
  }
  return total;
}

std::vector<std::vector<uint8_t>> EchoByteses(
    const std::vector<std::vector<uint8_t>>& xs) {
  return xs;
}

std::vector<uint64_t> EchoUints(const std::vector<uint64_t>& xs) {
  return xs;
}

std::vector<double> EchoDoubles(const std::vector<double>& xs) {
  return xs;
}

std::map<uint64_t, bool> EchoUintBoolMap(const std::map<uint64_t, bool>& m) {
  return m;
}

std::vector<std::string> EchoStrings(const std::vector<std::string>& xs) {
  return xs;
}

std::map<int64_t, int64_t> EchoIntMap(const std::map<int64_t, int64_t>& m) {
  return m;
}

std::vector<std::vector<int64_t>> EchoNested(
    const std::vector<std::vector<int64_t>>& xs) {
  return xs;
}

std::vector<int64_t> Iota(int64_t n) {
  std::vector<int64_t> out;
  out.reserve(static_cast<size_t>(n));
  for (int64_t i = 0; i < n; ++i) {
    out.push_back(i);
  }
  return out;
}

}  // namespace customfn
