// Author-side implementation of adder.idl.  This file is compiled to
// wasm32-wasip2 and sealed inside a Component-Model component: it
// cannot see the embedder's memory, cannot syscall, cannot do I/O.
// Everything else (codec, canonical-ABI stubs, the user_fns.h this
// includes) is generated by the cel_wasm_component macro.

#include "user_fns.h"

#include <cstdint>

namespace greeter {

int64_t Add(int64_t a, int64_t b) {
  return a + b;
}

}  // namespace greeter
