load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//compiler:__subpackages__"])

cc_library(
    name = "annotations",
    srcs = ["annotations.cc"],
    hdrs = ["annotations.h"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/strings",
    ],
)

cc_library(
    name = "typed_ast",
    srcs = ["typed_ast.cc"],
    hdrs = ["typed_ast.h"],
    deps = [
        ":annotations",
        "@cel-cpp//common:ast",
        "@cel-cpp//common:type",
        "@cel-cpp//common:type_kind",
        "@com_google_absl//absl/types:variant",
    ],
)

cc_library(
    name = "static_subset",
    srcs = ["static_subset.cc"],
    hdrs = ["static_subset.h"],
    deps = [
        "@cel-cpp//common:ast",
        "@cel-cpp//common:expr",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "annotations_test",
    srcs = ["annotations_test.cc"],
    deps = [
        ":annotations",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "typed_ast_test",
    srcs = ["typed_ast_test.cc"],
    deps = [
        ":annotations",
        ":typed_ast",
        "@cel-cpp//common:ast",
        "@cel-cpp//common:expr",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "static_subset_test",
    srcs = ["static_subset_test.cc"],
    deps = [
        ":static_subset",
        "@cel-cpp//common:ast",
        "@cel-cpp//common:expr",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:status_matchers",
        "@com_google_googletest//:gtest_main",
    ],
)
