// Embedded bytes for the wasm32 build of `cel_runtime.c`.
//
// Generated by //compiler/runtime:cel_runtime_wasm_bytes_cc from the
// output of //compiler/runtime:cel_runtime_wasm_file (a genrule that
// cross-compiles the C source with brew's `/opt/homebrew/opt/llvm/bin/clang`
// against a freestanding wasm32 target).  Codegen feeds these bytes into
// `BinaryenModuleRead` so every emitted module carries the full runtime
// (allocator + `cel_make_*` constructors + `cel_string_eq_v` + …).
//
// The bytes are linked in as a plain C array to keep the dependency
// surface small — no runfiles lookup, no `std::ifstream`, no filesystem
// dependency at load time.

#ifndef CELWASM_COMPILER_RUNTIME_CEL_RUNTIME_WASM_BYTES_H_
#define CELWASM_COMPILER_RUNTIME_CEL_RUNTIME_WASM_BYTES_H_

namespace celwasm {

extern const unsigned char kCelRuntimeWasmBytes[];
extern const unsigned int kCelRuntimeWasmBytesSize;

}  // namespace celwasm

#endif  // CELWASM_COMPILER_RUNTIME_CEL_RUNTIME_WASM_BYTES_H_
