// Compile-check for the genrule-emitted codec.h.  Includes the
// generated header against the hand-curated `customfn_stub.h` and
// references every lift / lower overload the codec is supposed to
// emit.  If the codec emitter regresses and produces text the C++
// compiler rejects, the build fails HERE — before any genrule
// consumer downstream sees a malformed file.
//
// The user's gating idea (m26 §3.5 / H.2.b design feedback,
// 2026-06-04): "Make sure the codec generated has bazel cpp_binary
// or cpp_library to ensure that it compiles right."  This TU is
// the cpp_library half of that gate; the genrule is the producer.

// The codec_dumper-driven genrule writes its output to a single
// header that this TU includes.  Path resolution goes through bazel
// (the genrule's `outs` becomes a `hdrs` of the cc_library).
#include "compiler/celfn/celfnc_emit/fixtures/customfn.h"
// NOLINTNEXTLINE(google-include-cleaner) — generated by genrule.
#include "compiler/celfn/celfnc_emit/generated_codec.h"

#include <map>
#include <string>
#include <string_view>
#include <vector>

#include "google/protobuf/duration.pb.h"
#include "google/protobuf/timestamp.pb.h"

namespace {

// Reference every codec overload that the dumper TU produces.  If
// the emitter renames or drops a signature, this fails to link.

[[maybe_unused]] void RefStringCodec() {
  customfn_string_t s{};
  std::string_view v = rules::codec::lift(s);
  (void)v;
  rules::codec::lower(&s, std::string_view("x"));
}

[[maybe_unused]] void RefBytesCodec() {
  customfn_list_u8_t l{};
  std::vector<uint8_t> v = rules::codec::lift(l);
  (void)v;
  rules::codec::lower(&l, std::vector<uint8_t>{});
}

[[maybe_unused]] void RefDurationCodec() {
  exports_cel_customfn_fns_duration_t r{};
  ::google::protobuf::Duration d = rules::codec::lift(r);
  (void)d;
  ::google::protobuf::Duration in;
  in.set_seconds(1);
  rules::codec::lower(&r, in);
}

[[maybe_unused]] void RefTimestampCodec() {
  exports_cel_customfn_fns_timestamp_t r{};
  ::google::protobuf::Timestamp t = rules::codec::lift(r);
  (void)t;
  ::google::protobuf::Timestamp in;
  in.set_seconds(0);
  rules::codec::lower(&r, in);
}

[[maybe_unused]] void RefListIntCodec() {
  customfn_list_s64_t l{};
  std::vector<int64_t> v = rules::codec::lift(l);
  (void)v;
  rules::codec::lower(&l, std::vector<int64_t>{});
}

[[maybe_unused]] void RefListStringCodec() {
  customfn_list_string_t l{};
  std::vector<std::string> v = rules::codec::lift(l);
  (void)v;
  rules::codec::lower(&l, std::vector<std::string>{});
}

[[maybe_unused]] void RefListListIntCodec() {
  customfn_list_list_s64_t l{};
  std::vector<std::vector<int64_t>> v = rules::codec::lift(l);
  (void)v;
  rules::codec::lower(&l, std::vector<std::vector<int64_t>>{});
}

[[maybe_unused]] void RefMapStringIntCodec() {
  customfn_list_tuple2_string_s64_t m{};
  std::map<std::string, int64_t> r = rules::codec::lift(m);
  (void)r;
  // Map LOWER not yet emitted (TODO in the emitter); no Ref needed.
}

[[maybe_unused]] void RefProtoCodec() {
  // Lift / lower are templates; instantiating requires a proto
  // message type.  Using a forward-declared struct compiles too —
  // the templates are only instantiated when called.
  struct FakeMsg {
    bool ParseFromArray(const void*, int) {
      return true;
    }
    bool SerializeToString(std::string*) const {
      return true;
    }
  };
  customfn_list_u8_t l{};
  FakeMsg m = rules::codec::lift_proto<FakeMsg>(l);
  rules::codec::lower_proto<FakeMsg>(&l, m);
}

}  // namespace
