// celfnc_emit/cpp_stub_emitter — see header for scope.

#include "compiler/celfn/celfnc_emit/cpp_stub_emitter.h"

#include <cctype>
#include <cstdint>
#include <string>
#include <vector>

#include "absl/log/absl_check.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/ascii.h"
#include "absl/strings/match.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_join.h"
#include "absl/strings/str_replace.h"
#include "absl/strings/string_view.h"
#include "absl/strings/substitute.h"
#include "compiler/celfn/function_library.h"

namespace celwasm::celfnc_emit {
namespace {

// Same package normalization rule the codec emitter uses
// (m26 §3.5.1): `cel:customfn` → `cel_customfn`.
std::string NormalizePkg(absl::string_view p) {
  return absl::StrReplaceAll(p, {{":", "_"}});
}

// Top-level argument/return categories.  Drives signature shape.
enum class Carrier : uint8_t {
  kScalarValue,  // bool / int64 / uint64 / double — pass by value
  kAuthorPtr,    // customfn_T* — pointer carrier
  kRecordPtr,    // exports_<pkg>_<iface>_T* — record pointer
  kProtoPtr,     // customfn_list_u8_t* — proto bytes
};

Carrier CarrierFor(const CelType& t) {
  using K = CelType::Kind;
  switch (t.kind()) {
    case K::kBool:
    case K::kInt:
    case K::kUint:
    case K::kDouble:
      return Carrier::kScalarValue;
    case K::kDuration:
    case K::kTimestamp:
      return Carrier::kRecordPtr;
    case K::kMessage:
      return Carrier::kProtoPtr;
    default:
      return Carrier::kAuthorPtr;
  }
}

// C type of an arg/return for a scalar-passing carrier.
absl::string_view ScalarCType(const CelType& t) {
  using K = CelType::Kind;
  switch (t.kind()) {
    case K::kBool:
      return "bool";
    case K::kInt:
      return "int64_t";
    case K::kUint:
      return "uint64_t";
    case K::kDouble:
      return "double";
    default:
      return "<unreachable>";
  }
}

std::string AuthorCStruct(const CelType& t);

// The element-name fragment of a nested carrier: `AuthorCStruct`
// minus the `customfn_` prefix and `_t` suffix, so it can be spliced
// into an enclosing list / tuple2 struct name.
std::string CStructSuffix(const CelType& t) {
  const std::string full = AuthorCStruct(t);
  absl::string_view v = full;
  if (absl::StartsWith(v, "customfn_")) v.remove_prefix(9);
  if (absl::EndsWith(v, "_t")) v.remove_suffix(2);
  return std::string(v);
}

// C struct name for an aggregate/string/bytes/list/map carrier.
// Mirrors cpp_codec_emitter's StructFor.
std::string AuthorCStruct(const CelType& t) {
  using K = CelType::Kind;
  switch (t.kind()) {
    case K::kString:
      return "customfn_string_t";
    case K::kBytes:
      return "customfn_list_u8_t";
    case K::kNull:
      return "customfn_option_u8_t";
    case K::kList:
      return absl::StrCat("customfn_list_", CStructSuffix(t.list_element()),
                          "_t");
    case K::kMap:
      return absl::StrCat("customfn_list_tuple2_", CStructSuffix(t.map_key()),
                          "_", CStructSuffix(t.map_value()), "_t");
    case K::kBool:
      return "customfn_bool_t";  // unused at top-level; only as list elt
    case K::kInt:
      return "customfn_s64_t";
    case K::kUint:
      return "customfn_u64_t";
    case K::kDouble:
      return "customfn_f64_t";
    case K::kMessage:
      return "customfn_list_u8_t";  // same wire shape as bytes
    case K::kDuration:
    case K::kTimestamp:
    case K::kOptional:
    case K::kType:
    case K::kUnknown:
      return "<unreachable>";
  }
  return "<unreachable>";
}

// Suffix used in customfn_list_<suffix>_t naming for list elements.
// For scalars, returns "s64" / "u64" / etc.  For complex types,
// mirrors cpp_codec_emitter's SuffixFor (string→"string",
// list<X>→"list_<X>", map<K,V>→"tuple2_<K>_<V>"... wait, the map
// inside list uses "tuple2_..." not "list_tuple2_..." because it's
// already wrapped in list<...>).
//
// Centralised here to avoid duplicating with codec; we deliberately
// inline it for clarity given the surface is small.

std::string RecordCType(const CelType& t, absl::string_view exports_prefix) {
  using K = CelType::Kind;
  switch (t.kind()) {
    case K::kDuration:
      return absl::StrCat(exports_prefix, "duration_t");
    case K::kTimestamp:
      return absl::StrCat(exports_prefix, "timestamp_t");
    default:
      return "<unreachable>";
  }
}

// ── Raw-string templates ──
//
// Per the m26 §3.5 template-pattern discipline (matches the
// wit + codec emitters): each emitted shape is a named
// `constexpr absl::string_view kFooTpl` raw-string here, and the
// emit fns SubstituteAndAppend with `$0`/`$1`... at the call site,
// so the C++ source mirrors the generated C++ directly.

// File-level preamble.
// $0 = optional block of #include "<extra>" lines (or empty).
constexpr absl::string_view kFilePreambleTpl =
    R"cpp(// Generated by `cel generate` — DO NOT EDIT.
          //
          // generated_stub.cc: routes each wit-bindgen-emitted export
          // through codec.h into the author's user_fns.cc impls.
          // Author never edits this file.

          $0 #include "customfn.h"
#include "codec.h"
#include "user_fns.h"

              extern "C" {
    )cpp";

// Scalar return: pass-through call.
// $0 = scalar C return type (bool / int64_t / uint64_t / double).
// $1 = export name (e.g. exports_cel_customfn_fns_fn_bool_bool).
// $2 = parameter signature ("bool x" / "int64_t a, int64_t b" / "").
// $3 = namespace::CamelFn (with leading "::" if global ns).
// $4 = comma-joined call args.
constexpr absl::string_view kExportScalarTpl =
    "$0 $1($2) {\n"
    "  return $3($4);\n"
    "}\n\n";

// Out-param return through the codec.
// $0 = export name.
// $1 = parameter signature including the trailing "<ret_type>* ret".
// $2 = namespace::CamelFn (with leading "::" if global ns).
// $3 = comma-joined call args.
constexpr absl::string_view kExportCodecTpl =
    "void $0($1) {\n"
    "  $2::codec::lower(ret, $3($4));\n"
    "}\n\n";

// Out-param proto return (lower_proto<M> instead of lower).
// $0 = export name.
// $1 = parameter signature including the trailing
//      "customfn_list_u8_t* ret".
// $2 = author cpp namespace (e.g. "rules").
// $3 = qualified proto message type (e.g. "acme::User").
// $4 = namespace::CamelFn.
// $5 = comma-joined call args.
constexpr absl::string_view kExportProtoTpl =
    "void $0($1) {\n"
    "  $2::codec::lower_proto<$3>(ret, $4($5));\n"
    "}\n\n";

// One emitted export-fn body.
// `optional` / `type` are rejected at declaration parse time, so a decl
// carrying one here means the front half of the pipeline let it through.
absl::Status RejectUnsupportedKinds(const CelfnDecl& d) {
  using K = CelType::Kind;
  if (d.return_type.kind() == K::kOptional ||
      d.return_type.kind() == K::kType) {
    return absl::FailedPreconditionError(
        absl::StrCat("stub emitter saw permanently-rejected return kind for `",
                     d.fn_name, "`"));
  }
  for (const auto& p : d.params) {
    if (p.type.kind() == K::kOptional || p.type.kind() == K::kType) {
      return absl::FailedPreconditionError(
          absl::StrCat("stub emitter saw permanently-rejected param kind for `",
                       d.fn_name, "`.", p.name));
    }
  }
  return absl::OkStatus();
}

// The C declarator and the call-site argument for one parameter: a
// scalar passes straight through, every carried kind lifts through the
// codec.
void AppendParamPieces(const CelfnParam& p, absl::string_view ns,
                       absl::string_view exports_prefix,
                       std::vector<std::string>& param_decls,
                       std::vector<std::string>& call_args) {
  switch (CarrierFor(p.type)) {
    case Carrier::kScalarValue:
      param_decls.push_back(absl::StrCat(ScalarCType(p.type), " ", p.name));
      call_args.emplace_back(p.name);
      return;
    case Carrier::kAuthorPtr:
      param_decls.push_back(absl::StrCat(AuthorCStruct(p.type), "* ", p.name));
      call_args.push_back(absl::StrCat(ns, "::codec::lift(*", p.name, ")"));
      return;
    case Carrier::kRecordPtr:
      param_decls.push_back(
          absl::StrCat(RecordCType(p.type, exports_prefix), "* ", p.name));
      call_args.push_back(absl::StrCat(ns, "::codec::lift(*", p.name, ")"));
      return;
    case Carrier::kProtoPtr:
      param_decls.push_back(absl::StrCat("customfn_list_u8_t* ", p.name));
      call_args.push_back(absl::StrCat(
          ns, "::codec::lift_proto<",
          absl::StrReplaceAll(p.type.message_fully_qualified_name(),
                              {{".", "::"}}),
          ">(*", p.name, ")"));
      return;
  }
  ABSL_CHECK(false) << "AppendParamPieces: unhandled carrier for param `"
                    << p.name << "`";
}

// The C type the out-param `ret` points at, for the non-scalar shapes.
std::string OutParamType(const CelType& ret, Carrier ret_c,
                         absl::string_view exports_prefix) {
  switch (ret_c) {
    case Carrier::kAuthorPtr:
      return AuthorCStruct(ret);
    case Carrier::kRecordPtr:
      return RecordCType(ret, exports_prefix);
    case Carrier::kProtoPtr:
      return "customfn_list_u8_t";
    case Carrier::kScalarValue:
      break;
  }
  ABSL_CHECK(false) << "OutParamType: scalar carrier has no out-param type";
  return {};
}

// One emitted export-fn body.
absl::StatusOr<std::string> EmitOneExport(const CelfnDecl& d,
                                          absl::string_view ns,
                                          absl::string_view exports_prefix) {
  if (auto s = RejectUnsupportedKinds(d); !s.ok()) return s;

  const std::string fn_camel = SnakeToCamel(d.fn_name);
  // The export symbol must match what wit-bindgen derives from the WIT
  // function name, and WIT identifiers are lowercase-only — so the WIT
  // emitter flattens case (wit_emitter.cc SnakeToKebab).  Overload ids
  // for proto-typed decls carry the proto type's CamelCase segment
  // (`is_adult_message_acme_User`), so the same flattening has to
  // happen here or the stub defines `..._acme_User` while wit-bindgen
  // declares `..._acme_user`, the export stays undefined, and the
  // component encoder reports it as an unresolved `env` import.
  const std::string export_name =
      absl::StrCat(exports_prefix, absl::AsciiStrToLower(d.overload_id));
  const Carrier ret_c = CarrierFor(d.return_type);

  // Argument list pieces.
  std::vector<std::string> param_decls;
  std::vector<std::string> call_args;  // codec::lift(*p) or p
  param_decls.reserve(d.params.size());
  call_args.reserve(d.params.size());
  for (const auto& p : d.params) {
    AppendParamPieces(p, ns, exports_prefix, param_decls, call_args);
  }

  // Signature.
  const std::string sig_args = absl::StrJoin(param_decls, ", ");
  const std::string called_fn = absl::StrCat(ns, "::", fn_camel);
  const std::string call_arg_list = absl::StrJoin(call_args, ", ");

  std::string out;
  if (ret_c == Carrier::kScalarValue) {
    absl::SubstituteAndAppend(&out, kExportScalarTpl,
                              ScalarCType(d.return_type), export_name, sig_args,
                              called_fn, call_arg_list);
    return out;
  }

  // Out-param shape.
  const std::string ret_type =
      OutParamType(d.return_type, ret_c, exports_prefix);
  const std::string ret_arg =
      sig_args.empty() ? absl::StrCat(ret_type, "* ret")
                       : absl::StrCat(sig_args, ", ", ret_type, "* ret");
  if (ret_c == Carrier::kProtoPtr) {
    const std::string proto_cpp = absl::StrReplaceAll(
        d.return_type.message_fully_qualified_name(), {{".", "::"}});
    absl::SubstituteAndAppend(&out, kExportProtoTpl, export_name, ret_arg, ns,
                              proto_cpp, called_fn, call_arg_list);
  } else {
    absl::SubstituteAndAppend(&out, kExportCodecTpl, export_name, ret_arg, ns,
                              called_fn, call_arg_list);
  }
  return out;
}

}  // namespace

std::string SnakeToCamel(absl::string_view snake) {
  std::string r;
  r.reserve(snake.size());
  bool cap = true;
  for (char c : snake) {
    if (c == '_') {
      cap = true;
      continue;
    }
    r.push_back(cap ? static_cast<char>(std::toupper(c)) : c);
    cap = false;
  }
  return r;
}

absl::StatusOr<std::string> EmitStubCc(
    const FunctionLibrary& lib, absl::string_view cpp_namespace,
    absl::string_view wit_package_name,
    const std::vector<std::string>& extra_includes) {
  const std::string exports_prefix =
      absl::StrCat("exports_", NormalizePkg(wit_package_name), "_fns_");

  std::string extras;
  for (const auto& inc : extra_includes) {
    absl::StrAppend(&extras, "#include \"", inc, "\"\n");
  }
  if (!extra_includes.empty()) absl::StrAppend(&extras, "\n");
  std::string out;
  absl::SubstituteAndAppend(&out, kFilePreambleTpl, extras);

  for (const auto& d : lib.decls()) {
    if (d.backend != CelfnDecl::Backend::kPlugin) continue;
    auto body = EmitOneExport(d, cpp_namespace, exports_prefix);
    if (!body.ok()) return body.status();
    absl::StrAppend(&out, *body);
  }
  absl::StrAppend(&out, "}  // extern \"C\"\n");
  return out;
}

}  // namespace celwasm::celfnc_emit
