// celfnc_emit/cpp_skeleton_emitter — see header for scope.

#include "compiler/celfn/celfnc_emit/cpp_skeleton_emitter.h"

#include <cctype>
#include <set>
#include <string>
#include <vector>

#include "absl/log/absl_check.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_join.h"
#include "absl/strings/str_replace.h"
#include "absl/strings/string_view.h"
#include "compiler/celfn/celfnc_emit/cpp_stub_emitter.h"  // SnakeToCamel
#include "compiler/celfn/function_library.h"

namespace celwasm::celfnc_emit {
namespace {

// CelfnType → idiomatic C++ author-facing type.  Used for params
// AND returns; param/return shape differs slightly:
//   - strings: param `std::string_view`, return `std::string`.
//   - aggregates: param `const std::vector<...>&` etc., return by
//     value.
//   - protos: param `const acme::User&`, return `acme::User`.
//   - scalars: always pass-by-value.
//
// `as_param` controls which shape we emit.
absl::StatusOr<std::string> CppType(const CelfnType& t, bool as_param) {
  using K = CelfnType::Kind;
  switch (t.kind) {
    case K::kBool:
      return std::string("bool");
    case K::kInt:
      return std::string("int64_t");
    case K::kUint:
      return std::string("uint64_t");
    case K::kDouble:
      return std::string("double");
    case K::kString:
      return std::string(as_param ? "std::string_view" : "std::string");
    case K::kBytes:
      return std::string(as_param ? "const std::vector<uint8_t>&"
                                  : "std::vector<uint8_t>");
    case K::kNull:
      return std::string("std::monostate");
    case K::kDuration:
      return std::string("absl::Duration");
    case K::kTimestamp:
      return std::string("absl::Time");
    case K::kList: {
      auto inner = CppType(t.list_element[0], /*as_param=*/false);
      if (!inner.ok()) return inner.status();
      const std::string body = absl::StrCat("std::vector<", *inner, ">");
      return std::string(as_param ? absl::StrCat("const ", body, "&") : body);
    }
    case K::kMap: {
      auto k = CppType(t.map_kv[0], /*as_param=*/false);
      auto v = CppType(t.map_kv[1], /*as_param=*/false);
      if (!k.ok()) return k.status();
      if (!v.ok()) return v.status();
      const std::string body = absl::StrCat("std::map<", *k, ", ", *v, ">");
      return std::string(as_param ? absl::StrCat("const ", body, "&") : body);
    }
    case K::kProto: {
      const std::string ns = absl::StrReplaceAll(t.proto_fqn, {{".", "::"}});
      return std::string(as_param ? absl::StrCat("const ", ns, "&") : ns);
    }
    case K::kOptional:
    case K::kType:
      return absl::FailedPreconditionError(
          "skeleton emitter saw a permanently-rejected CelfnType::Kind");
  }
  return absl::InternalError("CppType: unknown kind");
}

// Walk every type in lib; return true if any uses `Duration` /
// `Timestamp` (so we know whether to emit `absl/time/time.h`).
// Same idea for proto headers — but those are explicit
// `extra_includes` from the macro caller.
struct IncludeProbe {
  bool needs_absl_time = false;
  bool needs_variant = false;
  bool needs_map = false;
  bool needs_vector = false;
  bool needs_cstdint = false;
};

void ProbeType(const CelfnType& t, IncludeProbe* p) {
  using K = CelfnType::Kind;
  switch (t.kind) {
    case K::kBool:
      break;
    case K::kInt:
    case K::kUint:
      p->needs_cstdint = true;
      break;
    case K::kDouble:
      break;
    case K::kNull:
      p->needs_variant = true;
      break;
    case K::kDuration:
    case K::kTimestamp:
      p->needs_absl_time = true;
      break;
    case K::kBytes:
      p->needs_vector = true;
      p->needs_cstdint = true;
      break;
    case K::kList:
      p->needs_vector = true;
      if (!t.list_element.empty()) ProbeType(t.list_element[0], p);
      break;
    case K::kMap:
      p->needs_map = true;
      if (t.map_kv.size() == 2) {
        ProbeType(t.map_kv[0], p);
        ProbeType(t.map_kv[1], p);
      }
      break;
    case K::kString:
    case K::kProto:
    case K::kOptional:
    case K::kType:
      break;
  }
}

}  // namespace

absl::StatusOr<std::string> EmitUserFnsH(
    const FunctionLibrary& lib, absl::string_view cpp_namespace,
    const std::vector<std::string>& extra_includes) {
  IncludeProbe probe;
  for (const auto& d : lib.decls()) {
    if (d.backend != CelfnDecl::Backend::kForeignComponent) continue;
    ProbeType(d.return_type, &probe);
    for (const auto& p : d.params) ProbeType(p.type, &probe);
  }

  std::string out;
  absl::StrAppend(
      &out,
      "// Generated by `cel generate` — author-facing declarations.\n"
      "// Implement the bodies in user_fns.cc; everything else is\n"
      "// generated.  Re-running `cel generate` REGENERATES this file\n"
      "// and does NOT overwrite user_fns.cc.\n\n");
  absl::StrAppend(&out, "#pragma once\n\n");
  // Standard set: emitted unconditionally to match the codec.h /
  // generated_stub.cc convention.  Cheap, and avoids fragile
  // include-resolution churn when an author adds a new decl.
  absl::StrAppend(&out, "#include <cstdint>\n");
  absl::StrAppend(&out, "#include <map>\n");
  absl::StrAppend(&out, "#include <string>\n");
  absl::StrAppend(&out, "#include <string_view>\n");
  if (probe.needs_variant) absl::StrAppend(&out, "#include <variant>\n");
  absl::StrAppend(&out, "#include <vector>\n");
  absl::StrAppend(&out, "\n");
  if (probe.needs_absl_time) {
    absl::StrAppend(&out, "#include \"absl/time/time.h\"\n");
  }
  for (const auto& inc : extra_includes) {
    absl::StrAppend(&out, "#include \"", inc, "\"\n");
  }
  if (probe.needs_absl_time || !extra_includes.empty()) {
    absl::StrAppend(&out, "\n");
  }

  const bool has_ns = !cpp_namespace.empty();
  if (has_ns) {
    absl::StrAppend(&out, "namespace ", cpp_namespace, " {\n\n");
  }

  for (const auto& d : lib.decls()) {
    if (d.backend != CelfnDecl::Backend::kForeignComponent) continue;
    auto ret = CppType(d.return_type, /*as_param=*/false);
    if (!ret.ok()) return ret.status();
    std::vector<std::string> params;
    params.reserve(d.params.size());
    for (const auto& p : d.params) {
      auto pty = CppType(p.type, /*as_param=*/true);
      if (!pty.ok()) return pty.status();
      params.push_back(absl::StrCat(*pty, " ", p.name));
    }
    absl::StrAppend(&out, *ret, " ", SnakeToCamel(d.fn_name), "(",
                    absl::StrJoin(params, ", "), ");\n");
  }

  if (has_ns) {
    absl::StrAppend(&out, "\n}  // namespace ", cpp_namespace, "\n");
  }
  return out;
}

}  // namespace celwasm::celfnc_emit
