// celfnc_emit/wit_emitter — see header for scope.
//
// Discipline (m26 §3.5 template-pattern): each emitted shape is a
// named `constexpr absl::string_view kFooTpl` raw-string above; the
// emit fns use `absl::SubstituteAndAppend` with `$0`/`$1`... at the
// call site, so reading the C++ source you see the WIT directly.

#include "compiler/celfn/celfnc_emit/wit_emitter.h"

#include <set>
#include <string>
#include <vector>

#include "absl/log/absl_check.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_join.h"
#include "absl/strings/str_replace.h"
#include "absl/strings/string_view.h"
#include "absl/strings/substitute.h"
#include "compiler/celfn/function_library.h"

namespace celwasm::celfnc_emit {
namespace {

// ── Raw-string templates ──

// $0 = package_name (e.g. "cel:customfn")
// $1 = "@<version>" if package_version non-empty, "" otherwise
// $2 = interface body (records + fn signatures, already-indented)
constexpr absl::string_view kFilePreambleTpl =
    R"wit(// Generated by `cel generate` — DO NOT EDIT.
//
// Re-run `cel generate --language=cpp --idl=<your.idl>` to refresh.

package $0$1;

interface fns {
$2}

world customfn { export fns; }
world host   { import fns; }
)wit";

constexpr absl::string_view kDurationRecord =
    "  record duration { seconds: s64, nanos: s32 }\n";
constexpr absl::string_view kTimestampRecord =
    "  record timestamp { seconds: s64, nanos: s32 }\n";

// $0 = export name (kebab)
// $1 = params (e.g. "x: s64, y: list<string>")
// $2 = return WIT type
constexpr absl::string_view kFnSigTpl = "  $0: func($1) -> $2;\n";

// ── Records present in this lib ──
enum class RecordKind { kDuration, kTimestamp };

// Walk a CEL type → its WIT spelling, stamping `records` for every
// duration/timestamp encountered so the emitter can declare them.
absl::StatusOr<std::string> WitTypeText(const CelfnType& t,
                                        std::set<RecordKind>* records) {
  using K = CelfnType::Kind;
  switch (t.kind) {
    case K::kBool:
      return std::string("bool");
    case K::kInt:
      return std::string("s64");
    case K::kUint:
      return std::string("u64");
    case K::kDouble:
      return std::string("f64");
    case K::kNull:
      // CEL `null` rides as `option<u8>` — wit-bindgen 0.57 rejects
      // option<unit> at the C generator (m26 §3.5).
      return std::string("option<u8>");
    case K::kString:
      return std::string("string");
    case K::kBytes:
      return std::string("list<u8>");
    case K::kDuration:
      records->insert(RecordKind::kDuration);
      return std::string("duration");
    case K::kTimestamp:
      records->insert(RecordKind::kTimestamp);
      return std::string("timestamp");
    case K::kList: {
      if (t.list_element.empty()) {
        return absl::InternalError("list<> with empty element type");
      }
      auto inner = WitTypeText(t.list_element[0], records);
      if (!inner.ok()) return inner.status();
      return absl::StrCat("list<", *inner, ">");
    }
    case K::kMap: {
      if (t.map_kv.size() != 2) {
        return absl::InternalError("map<> with wrong kv arity");
      }
      auto k = WitTypeText(t.map_kv[0], records);
      auto v = WitTypeText(t.map_kv[1], records);
      if (!k.ok()) return k.status();
      if (!v.ok()) return v.status();
      // m24 §6: map<K,V> → list<tuple<K,V>>.
      return absl::StrCat("list<tuple<", *k, ", ", *v, ">>");
    }
    case K::kProto:
      // m24 §8: proto crosses as serialized bytes (list<u8>).  The
      // proto fqn is host-side metadata; it does NOT appear in WIT.
      return std::string("list<u8>");
    case K::kType:
    case K::kOptional:
      return absl::FailedPreconditionError(absl::StrCat(
          "wit emitter saw a permanently-rejected CelfnType::Kind (",
          (t.kind == K::kType ? "type" : "optional"),
          "); Builder::Build() should have rejected upstream (m24 §A.4 / "
          "§14)"));
  }
  return absl::InternalError("WitTypeText: unknown CelfnType::Kind");
}

absl::StatusOr<std::string> EmitOneFn(const CelfnDecl& d,
                                      std::set<RecordKind>* records) {
  ABSL_CHECK(d.backend == CelfnDecl::Backend::kPlugin)
      << "wit emitter only handles kPlugin decls";
  std::vector<std::string> param_parts;
  param_parts.reserve(d.params.size());
  for (const auto& p : d.params) {
    auto wit = WitTypeText(p.type, records);
    if (!wit.ok()) return wit.status();
    param_parts.push_back(absl::StrCat(p.name, ": ", *wit));
  }
  auto ret = WitTypeText(d.return_type, records);
  if (!ret.ok()) return ret.status();
  return absl::Substitute(kFnSigTpl, SnakeToKebab(d.overload_id),
                          absl::StrJoin(param_parts, ", "), *ret);
}

absl::string_view RecordLine(RecordKind k) {
  switch (k) {
    case RecordKind::kDuration:
      return kDurationRecord;
    case RecordKind::kTimestamp:
      return kTimestampRecord;
  }
  ABSL_CHECK(false) << "RecordKind switch fell through";
  return "";
}

}  // namespace

std::string SnakeToKebab(absl::string_view snake) {
  // WIT identifiers (per the WIT lexer): lowercase ASCII letters,
  // digits, and `-`.  Proto fqns we synthesise into overload ids
  // (e.g. `is_adult_message_acme_User`) carry the proto type's
  // CamelCase last segment — flatten it to lowercase here so the
  // wit-bindgen parser accepts the export name.
  std::string r = absl::StrReplaceAll(snake, {{"_", "-"}});
  for (char& c : r) {
    if (c >= 'A' && c <= 'Z') c = static_cast<char>(c - 'A' + 'a');
  }
  return r;
}

absl::StatusOr<std::string> EmitWit(const FunctionLibrary& lib,
                                    absl::string_view package_name,
                                    absl::string_view package_version) {
  std::set<RecordKind> records;
  std::vector<std::string> fn_lines;
  for (const auto& d : lib.decls()) {
    if (d.backend != CelfnDecl::Backend::kPlugin) continue;
    auto line = EmitOneFn(d, &records);
    if (!line.ok()) return line.status();
    fn_lines.push_back(*std::move(line));
  }

  // Build the interface body: records first (declared once each),
  // blank-line separator if both present, then the fn signatures.
  std::string body;
  for (RecordKind k : records) {
    absl::StrAppend(&body, RecordLine(k));
  }
  if (!records.empty() && !fn_lines.empty()) {
    absl::StrAppend(&body, "\n");
  }
  for (const auto& line : fn_lines) {
    absl::StrAppend(&body, line);
  }

  const std::string version_tag =
      package_version.empty() ? "" : absl::StrCat("@", package_version);
  return absl::Substitute(kFilePreambleTpl, package_name, version_tag, body);
}

}  // namespace celwasm::celfnc_emit
