// Embedded `CelRuntimeCatalogue` textproto (see
// `abi/runtime_catalogue.proto`), generated by
// `//abi:runtime_catalogue_textproto_cc` from
// `//abi:runtime_catalogue_textproto` — itself produced by
// `//bazel:gen_runtime_catalogue` from the `// cel:codegen-export`
// markers in `runtime/cel_*.{h,c}`.
//
// Embedded as a string literal (not read from a runfiles file) so
// `abi::CelRuntimeHelpers()` stays a pure in-process call with no
// cwd / runfiles dependency — its callers (`overload_table.cc`,
// `cel_abi_emit.cc`) are non-test library code that cannot assume a
// runfiles tree.  Parsed once at first use by `runtime_catalogue.cc`.

#ifndef CELWASM_ABI_RUNTIME_CATALOGUE_TEXTPROTO_H_
#define CELWASM_ABI_RUNTIME_CATALOGUE_TEXTPROTO_H_

#include "absl/strings/string_view.h"

namespace celwasm::abi {

// The generated catalogue textproto, as a string_view over a
// process-lifetime string literal.
absl::string_view RuntimeCatalogueTextproto();

}  // namespace celwasm::abi

#endif  // CELWASM_ABI_RUNTIME_CATALOGUE_TEXTPROTO_H_
